<?php

session_start();
include("connection.php");
error_reporting(1);
if (isset($_POST['action_type']) && !empty($_POST['action_type'])) {
	if ($_POST['action_type'] == 'data') {
		$get_query = "select * from rock WHERE id='$_POST[id]' AND `is_deleted`='0'";
		$select_result = mysqli_query($conn, $get_query);
		$result = mysqli_fetch_array($select_result);
		$id = $result['id'];
		$report_no = $result['report_no'];
		$job_no = $result['job_no'];
		$lab_no = $result['lab_no'];
		$fill = array(
			'id' => $id,
			'report_no' => $report_no,
			'job_no' => $job_no,
			'lab_no' => $lab_no,
			'ulr' => $result['ulr'],
			'amend_date' => $result['amend_date'],
			'bh_no' => $result['bh_no'],
			'rock_depth' => $result['rock_depth'],
			'chk_por' => $result['chk_por'],
			'chk_com' => $result['chk_com'],
			'desc1' => $result['desc1'],
			'desc2' => $result['desc2'],
			'desc3' => $result['desc3'],
			'con1' => $result['con1'],
			'con2' => $result['con2'],
			'con3' => $result['con3'],
			'depth1' => $result['depth1'],
			'depth2' => $result['depth2'],
			'depth3' => $result['depth3'],
			'length1' => $result['length1'],
			'length2' => $result['length2'],
			'length3' => $result['length3'],
			'dia1' => $result['dia1'],
			'dia2' => $result['dia2'],
			'dia3' => $result['dia3'],
			'ratio1' => $result['ratio1'],
			'ratio2' => $result['ratio2'],
			'ratio3' => $result['ratio3'],
			'corr1' => $result['corr1'],
			'corr2' => $result['corr2'],
			'corr3' => $result['corr3'],
			'area1' => $result['area1'],
			'area2' => $result['area2'],
			'area3' => $result['area3'],
			'fla1' => $result['fla1'],
			'fla2' => $result['fla2'],
			'fla3' => $result['fla3'],
			'par1' => $result['par1'],
			'par2' => $result['par2'],
			'par3' => $result['par3'],
			'ppl1' => $result['ppl1'],
			'ppl2' => $result['ppl2'],
			'ppl3' => $result['ppl3'],
			'str1' => $result['str1'],
			'str2' => $result['str2'],
			'str3' => $result['str3'],
			'rate1' => $result['rate1'],
			'rate2' => $result['rate2'],
			'rate3' => $result['rate3'],
			'mod1' => $result['mod1'],
			'mod2' => $result['mod2'],
			'mod3' => $result['mod3'],
			'load1' => $result['load1'],
			'load2' => $result['load2'],
			'load3' => $result['load3'],
			'ucs1' => $result['ucs1'],
			'ucs2' => $result['ucs2'],
			'ucs3' => $result['ucs3'],
			'cor1' => $result['cor1'],
			'cor2' => $result['cor2'],
			'cor3' => $result['cor3'],
			'avg_ucs' => $result['avg_ucs'],
			'chk_poi' => $result['chk_poi'],
			'gauge' => $result['gauge'],
			'sam1' => $result['sam1'],
			'sam2' => $result['sam2'],
			'sam3' => $result['sam3'],
			'sam4' => $result['sam4'],
			'sam5' => $result['sam5'],
			'sam6' => $result['sam6'],
			'sam7' => $result['sam7'],
			'sam8' => $result['sam8'],
			'sam9' => $result['sam9'],
			'sam10' => $result['sam10'],
			'sam11' => $result['sam11'],
			'd1' => $result['d1'],
			'd2' => $result['d2'],
			'd3' => $result['d3'],
			'd4' => $result['d4'],
			'd5' => $result['d5'],
			'd6' => $result['d6'],
			'd7' => $result['d7'],
			'd8' => $result['d8'],
			'd9' => $result['d9'],
			'd10' => $result['d10'],
			'd11' => $result['d11'],
			'h1' => $result['h1'],
			'h2' => $result['h2'],
			'h3' => $result['h3'],
			'h4' => $result['h4'],
			'h5' => $result['h5'],
			'h6' => $result['h6'],
			'h7' => $result['h7'],
			'h8' => $result['h8'],
			'h9' => $result['h9'],
			'h10' => $result['h10'],
			'h11' => $result['h11'],
			'di1' => $result['di1'],
			'di2' => $result['di2'],
			'di3' => $result['di3'],
			'di4' => $result['di4'],
			'di5' => $result['di5'],
			'di6' => $result['di6'],
			'di7' => $result['di7'],
			'di8' => $result['di8'],
			'di9' => $result['di9'],
			'di10' => $result['di10'],
			'di11' => $result['di11'],
			'f1' => $result['f1'],
			'f2' => $result['f2'],
			'f3' => $result['f3'],
			'f4' => $result['f4'],
			'f5' => $result['f5'],
			'f6' => $result['f6'],
			'f7' => $result['f7'],
			'f8' => $result['f8'],
			'f9' => $result['f9'],
			'f10' => $result['f10'],
			'f11' => $result['f11'],
			'pload1' => $result['pload1'],
			'pload2' => $result['pload2'],
			'pload3' => $result['pload3'],
			'pload4' => $result['pload4'],
			'pload5' => $result['pload5'],
			'pload6' => $result['pload6'],
			'pload7' => $result['pload7'],
			'pload8' => $result['pload8'],
			'pload9' => $result['pload9'],
			'pload10' => $result['pload10'],
			'pload11' => $result['pload11'],
			'sur1' => $result['sur1'],
			'sur2' => $result['sur2'],
			'sur3' => $result['sur3'],
			'sur4' => $result['sur4'],
			'sur5' => $result['sur5'],
			'sur6' => $result['sur6'],
			'sur7' => $result['sur7'],
			'sur8' => $result['sur8'],
			'sur9' => $result['sur9'],
			'sur10' => $result['sur10'],
			'sur11' => $result['sur11'],
			'fload1' => $result['fload1'],
			'fload2' => $result['fload2'],
			'fload3' => $result['fload3'],
			'fload4' => $result['fload4'],
			'fload5' => $result['fload5'],
			'fload6' => $result['fload6'],
			'fload7' => $result['fload7'],
			'fload8' => $result['fload8'],
			'fload9' => $result['fload9'],
			'fload10' => $result['fload10'],
			'fload11' => $result['fload11'],
			'pstr1' => $result['pstr1'],
			'pstr2' => $result['pstr2'],
			'pstr3' => $result['pstr3'],
			'pstr4' => $result['pstr4'],
			'pstr5' => $result['pstr5'],
			'pstr6' => $result['pstr6'],
			'pstr7' => $result['pstr7'],
			'pstr8' => $result['pstr8'],
			'pstr9' => $result['pstr9'],
			'pstr10' => $result['pstr10'],
			'pstr11' => $result['pstr11'],
			'ucom1' => $result['ucom1'],
			'ucom2' => $result['ucom2'],
			'ucom3' => $result['ucom3'],
			'ucom4' => $result['ucom4'],
			'ucom5' => $result['ucom5'],
			'ucom6' => $result['ucom6'],
			'ucom7' => $result['ucom7'],
			'ucom8' => $result['ucom8'],
			'ucom9' => $result['ucom9'],
			'ucom10' => $result['ucom10'],
			'ucom11' => $result['ucom11'],
			// 'chk_spg' => $result['chk_spg'],
			'chk_tes' => $result['chk_tes'],
			// 'avg_spg' => $result['avg_spg'],
			'chk_sp' => $result['chk_sp'],
			'sp_specific_gravity' => $result['sp_specific_gravity'],
			'sp_specific_gravity_1' => $result['sp_specific_gravity_1'],
			'sp_specific_gravity_2' => $result['sp_specific_gravity_2'],
			'sp_specific_gravity_3' => $result['sp_specific_gravity_3'],
			'sp_water_abr_1' => $result['sp_water_abr_1'],
			'sp_water_abr_2' => $result['sp_water_abr_2'],
			'sp_water_abr_3' => $result['sp_water_abr_3'],
			'sp_water_abr' => $result['sp_water_abr'],
			'sp_w_sur_1' => $result['sp_w_sur_1'],
			'sp_w_sur_2' => $result['sp_w_sur_2'],
			'sp_w_sur_3' => $result['sp_w_sur_3'],
			'sp_wt_st_1' => $result['sp_wt_st_1'],
			'sp_wt_st_2' => $result['sp_wt_st_2'],
			'sp_wt_st_3' => $result['sp_wt_st_3'],
			'sp_w_s_1' => $result['sp_w_s_1'],
			'sp_w_s_2' => $result['sp_w_s_2'],
			'sp_w_s_3' => $result['sp_w_s_3'],
			'sp_agg1' => $result['sp_agg1'],
			'sp_agg2' => $result['sp_agg2'],
			'sp_agg3' => $result['sp_agg3'],
			'sp_wat1' => $result['sp_wat1'],
			'sp_wat2' => $result['sp_wat2'],
			'sp_wat3' => $result['sp_wat3'],
			'avg_tes' => $result['avg_tes'],
			'com_1' => $result['com_1'],
			'com_2' => $result['com_2'],
			'com_3' => $result['com_3'],
			'com_4' => $result['com_4'],
			'com_5' => $result['com_5'],
			'com_6' => $result['com_6'],
			'com_7' => $result['com_7'],
			'com_8' => $result['com_8'],
			'com_9' => $result['com_9'],
			'com_10' => $result['com_10'],
			'com_11' => $result['com_11'],
			'com_12' => $result['com_12'],
			'com_13' => $result['com_13'],
			'com_14' => $result['com_14'],
			'com_15' => $result['com_15'],
			'com_16' => $result['com_16'],
			'com_17' => $result['com_17'],
			'com_18' => $result['com_18'],
			'com_19' => $result['com_19'],
			'com_20' => $result['com_20'],
			'com_21' => $result['com_21'],
			'com_22' => $result['com_22'],
			'com_23' => $result['com_23'],
			'com_24' => $result['com_24'],
			'com_25' => $result['com_25'],
			'com_26' => $result['com_26'],
			'com_27' => $result['com_27'],
			'com_28' => $result['com_28'],
			'com_29' => $result['com_29'],
			'com_30' => $result['com_30'],
			'com_31' => $result['com_31'],
			'com_32' => $result['com_32'],
			'com_33' => $result['com_33'],
			'com_34' => $result['com_34'],
			'com_35' => $result['com_35'],
			'com_36' => $result['com_36'],
			'com_37' => $result['com_37'],
			'com_38' => $result['com_38'],
			'com_39' => $result['com_39'],
			'com_40' => $result['com_40'],
			'com_41' => $result['com_41'],
			'com_42' => $result['com_42'],
			'com_43' => $result['com_43'],
			'com_44' => $result['com_44'],
			'com_45' => $result['com_45'],
			'com_46' => $result['com_46'],
			'com_47' => $result['com_47'],
			'com_48' => $result['com_48'],
			'com_49' => $result['com_49'],
			'com_50' => $result['com_50'],
			'com_51' => $result['com_51'],
			'com_52' => $result['com_52'],
			'com_53' => $result['com_53'],
			'com_54' => $result['com_54'],
			'com_55' => $result['com_55'],
			'com_56' => $result['com_56'],
			'com_57' => $result['com_57'],
			'com_58' => $result['com_58'],
			'com_59' => $result['com_59'],
			'com_60' => $result['com_60'],
			'com_61' => $result['com_61'],
			'com_62' => $result['com_62'],
			'com_63' => $result['com_63'],
			'com_64' => $result['com_64'],
			'com_65' => $result['com_65'],
			'com_66' => $result['com_66'],
			'com_67' => $result['com_67'],
			'com_68' => $result['com_68'],
			'com_69' => $result['com_69'],
			'com_70' => $result['com_70'],
			'com_71' => $result['com_71'],
			'com_72' => $result['com_72'],
			'com_73' => $result['com_73'],
			'com_74' => $result['com_74'],
			'com_75' => $result['com_75'],
			'com_76' => $result['com_76'],
			'com_77' => $result['com_77'],
			'com_78' => $result['com_78'],
			'com_79' => $result['com_79'],
			'com_80' => $result['com_80'],
			'com_81' => $result['com_81'],
			'com_82' => $result['com_82'],
			'com_83' => $result['com_83'],
			'com_84' => $result['com_84'],
			'com_85' => $result['com_85'],
			'com_86' => $result['com_86'],
			'com_87' => $result['com_87'],
			'com_88' => $result['com_88'],
			'com_89' => $result['com_89'],
			'com_90' => $result['com_90'],
			'com_91' => $result['com_91'],
			'com_92' => $result['com_92'],
			'com_93' => $result['com_93'],
			'com_94' => $result['com_94'],
			'com_95' => $result['com_95'],
			'com_96' => $result['com_96'],
			'com_97' => $result['com_97'],
			'com_98' => $result['com_98'],
			'com_99' => $result['com_99'],
			'com_100' => $result['com_100'],
			'com_101' => $result['com_101'],
			'com_102' => $result['com_102'],
			'com_103' => $result['com_103'],
			'com_104' => $result['com_104'],
			'com_105' => $result['com_105'],
			'com_106' => $result['com_106'],
			'com_107' => $result['com_107'],
			'com_108' => $result['com_108'],
			'com_109' => $result['com_109'],
			'sp_wt_st_4' => $result['sp_wt_st_4'],
			'sp_wt_st_5' => $result['sp_wt_st_5'],
			'sp_wt_st_6' => $result['sp_wt_st_6'],
			'sp_wt_st_7' => $result['sp_wt_st_7'],
			'sp_wt_st_8' => $result['sp_wt_st_8'],
			'sp_wt_st_9' => $result['sp_wt_st_9'],
			'sp_w_s_4' => $result['sp_w_s_4'],
			'sp_w_s_5' => $result['sp_w_s_5'],
			'sp_w_s_6' => $result['sp_w_s_6'],
			'sp_w_s_7' => $result['sp_w_s_7'],
			'sp_w_s_8' => $result['sp_w_s_8'],
			'sp_w_s_9' => $result['sp_w_s_9'],
			'sp_w_sur_4' => $result['sp_w_sur_4'],
			'sp_w_sur_5' => $result['sp_w_sur_5'],
			'sp_w_sur_6' => $result['sp_w_sur_6'],
			'sp_w_sur_7' => $result['sp_w_sur_7'],
			'sp_w_sur_8' => $result['sp_w_sur_8'],
			'sp_w_sur_9' => $result['sp_w_sur_9'],
			'sp_agg4' => $result['sp_agg4'],
			'sp_agg5' => $result['sp_agg5'],
			'sp_agg6' => $result['sp_agg6'],
			'sp_agg7' => $result['sp_agg7'],
			'sp_agg8' => $result['sp_agg8'],
			'sp_agg9' => $result['sp_agg9'],
			'sp_wat4' => $result['sp_wat4'],
			'sp_wat5' => $result['sp_wat5'],
			'sp_wat6' => $result['sp_wat6'],
			'sp_wat7' => $result['sp_wat7'],
			'sp_wat8' => $result['sp_wat8'],
			'sp_wat9' => $result['sp_wat9'],
			'sp_specific_gravity_4' => $result['sp_specific_gravity_4'],
			'sp_specific_gravity_5' => $result['sp_specific_gravity_5'],
			'sp_specific_gravity_6' => $result['sp_specific_gravity_6'],
			'sp_specific_gravity_7' => $result['sp_specific_gravity_7'],
			'sp_specific_gravity_8' => $result['sp_specific_gravity_8'],
			'sp_specific_gravity_9' => $result['sp_specific_gravity_9'],
			'sp_water_abr_4' => $result['sp_water_abr_4'],
			'sp_water_abr_5' => $result['sp_water_abr_5'],
			'sp_water_abr_6' => $result['sp_water_abr_6'],
			'sp_water_abr_7' => $result['sp_water_abr_7'],
			'sp_water_abr_8' => $result['sp_water_abr_8'],
			'sp_water_abr_9' => $result['sp_water_abr_9'],
			'sp_sg_avg_2' => $result['sp_sg_avg_2'],
			'sp_sg_avg_3' => $result['sp_sg_avg_3'],
			'sp_wa_avg_2' => $result['sp_wa_avg_2'],
			'sp_wa_avg_3' => $result['sp_wa_avg_3'],
			'sp_porosity_1' => $result['sp_porosity_1'],
			'sp_porosity_2' => $result['sp_porosity_2'],
			'sp_porosity_3' => $result['sp_porosity_3'],
			'sp_temp' => $result['sp_temp'],
			'remark' => $result['remark'],
			'Sheet_no' => $result['Sheet_no'],
			'wt_m' => $result['wt_m'],
			
			'wtr_temp_1' => $result['wtr_temp_1'],
			'wtr_temp_2' => $result['wtr_temp_2'],
			'wtr_temp_3' => $result['wtr_temp_3'],
			'rt_m_1' => $result['rt_m_1'],
			'rt_m_2' => $result['rt_m_2'],
			'rt_m_3' => $result['rt_m_3'],
			'ss_m1_1' => $result['ss_m1_1'],
			'ss_m1_2' => $result['ss_m1_2'],
			'ss_m1_3' => $result['ss_m1_3'],
			'ss_m2_1' => $result['ss_m2_1'],
			'ss_m2_2' => $result['ss_m2_2'],
			'ss_m2_3' => $result['ss_m2_3'],
			'ss_m3_1' => $result['ss_m3_1'],
			'ss_m3_2' => $result['ss_m3_2'],
			'ss_m3_3' => $result['ss_m3_3'],
			'ss_m4_1' => $result['ss_m4_1'],
			'ss_m4_2' => $result['ss_m4_2'],
			'ss_m4_3' => $result['ss_m4_3'],
			'ss_m5_1' => $result['ss_m5_1'],
			'ss_m5_2' => $result['ss_m5_2'],
			'ss_m5_3' => $result['ss_m5_3'],
			'ssm_sub_1' => $result['ssm_sub_1'],
			'ssm_sub_2' => $result['ssm_sub_2'],
			'ssm_sub_3' => $result['ssm_sub_3'],
			'ssm_sat_1' => $result['ssm_sat_1'],
			'ssm_sat_2' => $result['ssm_sat_2'],
			'ssm_sat_3' => $result['ssm_sat_3'],
			'dm_ms_1' => $result['dm_ms_1'],
			'dm_ms_2' => $result['dm_ms_2'],
			'dm_ms_3' => $result['dm_ms_3'],
			'bvol_1' => $result['bvol_1'],
			'bvol_2' => $result['bvol_2'],
			'bvol_3' => $result['bvol_3'],
			'pv_1' => $result['pv_1'],
			'pv_2' => $result['pv_2'],
			'pv_3' => $result['pv_3'],
			'por_1' => $result['por_1'],
			'por_2' => $result['por_2'],
			'por_3' => $result['por_3'],
			'pd_1' => $result['pd_1'],
			'pd_2' => $result['pd_2'],
			'pd_3' => $result['pd_3'],
			'wc_1' => $result['wc_1'],
			'wc_2' => $result['wc_2'],
			'wc_3' => $result['wc_3']

		);
		echo json_encode($fill);
	} else if ($_POST['action_type'] == 'add') {
		$report_no = $_POST['report_no'];
		$job_no = $_POST['job_no'];
		$lab_no = $_POST['lab_no'];
		$ulr =  $_POST['ulr'];
		$amend_date =  $_POST['amend_date'];

		$bh_no = $_POST['bh_no'];
		$rock_depth = $_POST['rock_depth'];
		$chk_por = $_POST['chk_por'];
		$chk_com = $_POST['chk_com'];
		$desc1 = $_POST['desc1'];
		$desc2 = $_POST['desc2'];
		$desc3 = $_POST['desc3'];
		$con1 = $_POST['con1'];
		$con2 = $_POST['con2'];
		$con3 = $_POST['con3'];
		$depth1 = $_POST['depth1'];
		$depth2 = $_POST['depth2'];
		$depth3 = $_POST['depth3'];
		$length1 = $_POST['length1'];
		$length2 = $_POST['length2'];
		$length3 = $_POST['length3'];
		$dia1 = $_POST['dia1'];
		$dia2 = $_POST['dia2'];
		$dia3 = $_POST['dia3'];
		$ratio1 = $_POST['ratio1'];
		$ratio2 = $_POST['ratio2'];
		$ratio3 = $_POST['ratio3'];
		$corr1 = $_POST['corr1'];
		$corr2 = $_POST['corr2'];
		$corr3 = $_POST['corr3'];
		$area1 = $_POST['area1'];
		$area2 = $_POST['area2'];
		$area3 = $_POST['area3'];
		$fla1 = $_POST['fla1'];
		$fla2 = $_POST['fla2'];
		$fla3 = $_POST['fla3'];
		$par1 = $_POST['par1'];
		$par2 = $_POST['par2'];
		$par3 = $_POST['par3'];
		$ppl1 = $_POST['ppl1'];
		$ppl2 = $_POST['ppl2'];
		$ppl3 = $_POST['ppl3'];
		$str1 = $_POST['str1'];
		$str2 = $_POST['str2'];
		$str3 = $_POST['str3'];
		$rate1 = $_POST['rate1'];
		$rate2 = $_POST['rate2'];
		$rate3 = $_POST['rate3'];
		$mod1 = $_POST['mod1'];
		$mod2 = $_POST['mod2'];
		$mod3 = $_POST['mod3'];
		$load1 = $_POST['load1'];
		$load2 = $_POST['load2'];
		$load3 = $_POST['load3'];
		$ucs1 = $_POST['ucs1'];
		$ucs2 = $_POST['ucs2'];
		$ucs3 = $_POST['ucs3'];
		$cor1 = $_POST['cor1'];
		$cor2 = $_POST['cor2'];
		$cor3 = $_POST['cor3'];
		$avg_ucs = $_POST['avg_ucs'];
		$chk_poi = $_POST['chk_poi'];
		$gauge = $_POST['gauge'];
		$sam1 = $_POST['sam1'];
		$sam2 = $_POST['sam2'];
		$sam3 = $_POST['sam3'];
		$sam4 = $_POST['sam4'];
		$sam5 = $_POST['sam5'];
		$sam6 = $_POST['sam6'];
		$sam7 = $_POST['sam7'];
		$sam8 = $_POST['sam8'];
		$sam9 = $_POST['sam9'];
		$sam10 = $_POST['sam10'];
		$sam11 = $_POST['sam11'];
		$d1 = $_POST['d1'];
		$d2 = $_POST['d2'];
		$d3 = $_POST['d3'];
		$d4 = $_POST['d4'];
		$d5 = $_POST['d5'];
		$d6 = $_POST['d6'];
		$d7 = $_POST['d7'];
		$d8 = $_POST['d8'];
		$d9 = $_POST['d9'];
		$d10 = $_POST['d10'];
		$d11 = $_POST['d11'];
		$h1 = $_POST['h1'];
		$h2 = $_POST['h2'];
		$h3 = $_POST['h3'];
		$h4 = $_POST['h4'];
		$h5 = $_POST['h5'];
		$h6 = $_POST['h6'];
		$h7 = $_POST['h7'];
		$h8 = $_POST['h8'];
		$h9 = $_POST['h9'];
		$h10 = $_POST['h10'];
		$h11 = $_POST['h11'];
		$di1 = $_POST['di1'];
		$di2 = $_POST['di2'];
		$di3 = $_POST['di3'];
		$di4 = $_POST['di4'];
		$di5 = $_POST['di5'];
		$di6 = $_POST['di6'];
		$di7 = $_POST['di7'];
		$di8 = $_POST['di8'];
		$di9 = $_POST['di9'];
		$di10 = $_POST['di10'];
		$di11 = $_POST['di11'];
		$f1 = $_POST['f1'];
		$f2 = $_POST['f2'];
		$f3 = $_POST['f3'];
		$f4 = $_POST['f4'];
		$f5 = $_POST['f5'];
		$f6 = $_POST['f6'];
		$f7 = $_POST['f7'];
		$f8 = $_POST['f8'];
		$f9 = $_POST['f9'];
		$f10 = $_POST['f10'];
		$f11 = $_POST['f11'];
		$pload1 = $_POST['pload1'];
		$pload2 = $_POST['pload2'];
		$pload3 = $_POST['pload3'];
		$pload4 = $_POST['pload4'];
		$pload5 = $_POST['pload5'];
		$pload6 = $_POST['pload6'];
		$pload7 = $_POST['pload7'];
		$pload8 = $_POST['pload8'];
		$pload9 = $_POST['pload9'];
		$pload10 = $_POST['pload10'];
		$pload11 = $_POST['pload11'];
		$sur1 = $_POST['sur1'];
		$sur2 = $_POST['sur2'];
		$sur3 = $_POST['sur3'];
		$sur4 = $_POST['sur4'];
		$sur5 = $_POST['sur5'];
		$sur6 = $_POST['sur6'];
		$sur7 = $_POST['sur7'];
		$sur8 = $_POST['sur8'];
		$sur9 = $_POST['sur9'];
		$sur10 = $_POST['sur10'];
		$sur11 = $_POST['sur11'];
		$fload1 = $_POST['fload1'];
		$fload2 = $_POST['fload2'];
		$fload3 = $_POST['fload3'];
		$fload4 = $_POST['fload4'];
		$fload5 = $_POST['fload5'];
		$fload6 = $_POST['fload6'];
		$fload7 = $_POST['fload7'];
		$fload8 = $_POST['fload8'];
		$fload9 = $_POST['fload9'];
		$fload10 = $_POST['fload10'];
		$fload11 = $_POST['fload11'];
		$pstr1 = $_POST['pstr1'];
		$pstr2 = $_POST['pstr2'];
		$pstr3 = $_POST['pstr3'];
		$pstr4 = $_POST['pstr4'];
		$pstr5 = $_POST['pstr5'];
		$pstr6 = $_POST['pstr6'];
		$pstr7 = $_POST['pstr7'];
		$pstr8 = $_POST['pstr8'];
		$pstr9 = $_POST['pstr9'];
		$pstr10 = $_POST['pstr10'];
		$pstr11 = $_POST['pstr11'];
		$ucom1 = $_POST['ucom1'];
		$ucom2 = $_POST['ucom2'];
		$ucom3 = $_POST['ucom3'];
		$ucom4 = $_POST['ucom4'];
		$ucom5 = $_POST['ucom5'];
		$ucom6 = $_POST['ucom6'];
		$ucom7 = $_POST['ucom7'];
		$ucom8 = $_POST['ucom8'];
		$ucom9 = $_POST['ucom9'];
		$ucom10 = $_POST['ucom10'];
		$ucom11 = $_POST['ucom11'];
		// $chk_spg = $_POST['chk_spg'];
		$chk_tes = $_POST['chk_tes'];
		// $avg_spg = $_POST['avg_spg'];
		$avg_tes = $_POST['avg_tes'];
		
		$chk_sp =  $_POST['chk_sp'];
		$sp_wt_st_1 = $_POST['sp_wt_st_1'];
		$sp_wt_st_2 = $_POST['sp_wt_st_2'];
		$sp_wt_st_3 = $_POST['sp_wt_st_3'];
		$sp_w_sur_2 = $_POST['sp_w_sur_2'];
		$sp_w_sur_3 = $_POST['sp_w_sur_3'];
		$sp_agg2 = $_POST['sp_agg2'];
		$sp_agg3 = $_POST['sp_agg3'];
		$sp_wat2 = $_POST['sp_wat2'];
		$sp_wat3 = $_POST['sp_wat3'];
		$sp_w_s_2 = $_POST['sp_w_s_2'];
		$sp_w_s_3 = $_POST['sp_w_s_3'];
		$sp_specific_gravity_1 = $_POST['sp_specific_gravity_1'];
		$sp_specific_gravity_2 = $_POST['sp_specific_gravity_2'];
		$sp_specific_gravity_3 = $_POST['sp_specific_gravity_3'];
		$sp_water_abr_1 = $_POST['sp_water_abr_1'];
		$sp_water_abr_2 = $_POST['sp_water_abr_2'];
		$sp_water_abr_3 = $_POST['sp_water_abr_3'];
		$sp_water_abr = $_POST['sp_water_abr'];
		$sp_w_sur_1 = $_POST['sp_w_sur_1'];
		$sp_w_s_1 = $_POST['sp_w_s_1'];
		$sp_agg1 = $_POST['sp_agg1'];
		$sp_wat1 = $_POST['sp_wat1'];
		$sp_specific_gravity = $_POST['sp_specific_gravity'];

		$com_1 = $_POST['com_1'];
$com_2 = $_POST['com_2'];
$com_3 = $_POST['com_3'];
$com_4 = $_POST['com_4'];
$com_5 = $_POST['com_5'];
$com_6 = $_POST['com_6'];
$com_7 = $_POST['com_7'];
$com_8 = $_POST['com_8'];
$com_9 = $_POST['com_9'];
$com_10 = $_POST['com_10'];
$com_11 = $_POST['com_11'];
$com_12 = $_POST['com_12'];
$com_13 = $_POST['com_13'];
$com_14 = $_POST['com_14'];
$com_15 = $_POST['com_15'];
$com_16 = $_POST['com_16'];
$com_17 = $_POST['com_17'];
$com_18 = $_POST['com_18'];
$com_19 = $_POST['com_19'];
$com_20 = $_POST['com_20'];
$com_21 = $_POST['com_21'];
$com_22 = $_POST['com_22'];
$com_23 = $_POST['com_23'];
$com_24 = $_POST['com_24'];
$com_25 = $_POST['com_25'];
$com_26 = $_POST['com_26'];
$com_27 = $_POST['com_27'];
$com_28 = $_POST['com_28'];
$com_29 = $_POST['com_29'];
$com_30 = $_POST['com_30'];
$com_31 = $_POST['com_31'];
$com_32 = $_POST['com_32'];
$com_33 = $_POST['com_33'];
$com_34 = $_POST['com_34'];
$com_35 = $_POST['com_35'];
$com_36 = $_POST['com_36'];
$com_37 = $_POST['com_37'];
$com_38 = $_POST['com_38'];
$com_39 = $_POST['com_39'];
$com_40 = $_POST['com_40'];
$com_41 = $_POST['com_41'];
$com_42 = $_POST['com_42'];
$com_43 = $_POST['com_43'];
$com_44 = $_POST['com_44'];
$com_45 = $_POST['com_45'];
$com_46 = $_POST['com_46'];
$com_47 = $_POST['com_47'];
$com_48 = $_POST['com_48'];
$com_49 = $_POST['com_49'];
$com_50 = $_POST['com_50'];
$com_51 = $_POST['com_51'];
$com_52 = $_POST['com_52'];
$com_53 = $_POST['com_53'];
$com_54 = $_POST['com_54'];
$com_55 = $_POST['com_55'];
$com_56 = $_POST['com_56'];
$com_57 = $_POST['com_57'];
$com_58 = $_POST['com_58'];
$com_59 = $_POST['com_59'];
$com_60 = $_POST['com_60'];
$com_61 = $_POST['com_61'];
$com_62 = $_POST['com_62'];
$com_63 = $_POST['com_63'];
$com_64 = $_POST['com_64'];
$com_65 = $_POST['com_65'];
$com_66 = $_POST['com_66'];
$com_67 = $_POST['com_67'];
$com_68 = $_POST['com_68'];
$com_69 = $_POST['com_69'];
$com_70 = $_POST['com_70'];
$com_71 = $_POST['com_71'];
$com_72 = $_POST['com_72'];
$com_73 = $_POST['com_73'];
$com_74 = $_POST['com_74'];
$com_75 = $_POST['com_75'];
$com_76 = $_POST['com_76'];
$com_77 = $_POST['com_77'];
$com_78 = $_POST['com_78'];
$com_79 = $_POST['com_79'];
$com_80 = $_POST['com_80'];
$com_81 = $_POST['com_81'];
$com_82 = $_POST['com_82'];
$com_83 = $_POST['com_83'];
$com_84 = $_POST['com_84'];
$com_85 = $_POST['com_85'];
$com_86 = $_POST['com_86'];
$com_87 = $_POST['com_87'];
$com_88 = $_POST['com_88'];
$com_89 = $_POST['com_89'];
$com_90 = $_POST['com_90'];
$com_91 = $_POST['com_91'];
$com_92 = $_POST['com_92'];
$com_93 = $_POST['com_93'];
$com_94 = $_POST['com_94'];
$com_95 = $_POST['com_95'];
$com_96 = $_POST['com_96'];
$com_97 = $_POST['com_97'];
$com_98 = $_POST['com_98'];
$com_99 = $_POST['com_99'];
$com_100 = $_POST['com_100'];
$com_101 = $_POST['com_101'];
$com_102 = $_POST['com_102'];
$com_103 = $_POST['com_103'];
$com_104 = $_POST['com_104'];
$com_105 = $_POST['com_105'];
$com_106 = $_POST['com_106'];
$com_107 = $_POST['com_107'];
$com_108 = $_POST['com_108'];
$com_109 = $_POST['com_109'];

$sp_wt_st_4 = $_POST['sp_wt_st_4'];
$sp_wt_st_5 = $_POST['sp_wt_st_5'];
$sp_wt_st_6 = $_POST['sp_wt_st_6'];
$sp_wt_st_7 = $_POST['sp_wt_st_7'];
$sp_wt_st_8 = $_POST['sp_wt_st_8'];
$sp_wt_st_9 = $_POST['sp_wt_st_9'];
$sp_w_s_4 = $_POST['sp_w_s_4'];
$sp_w_s_5 = $_POST['sp_w_s_5'];
$sp_w_s_6 = $_POST['sp_w_s_6'];
$sp_w_s_7 = $_POST['sp_w_s_7'];
$sp_w_s_8 = $_POST['sp_w_s_8'];
$sp_w_s_9 = $_POST['sp_w_s_9'];
$sp_w_sur_4 = $_POST['sp_w_sur_4'];
$sp_w_sur_5 = $_POST['sp_w_sur_5'];
$sp_w_sur_6 = $_POST['sp_w_sur_6'];
$sp_w_sur_7 = $_POST['sp_w_sur_7'];
$sp_w_sur_8 = $_POST['sp_w_sur_8'];
$sp_w_sur_9 = $_POST['sp_w_sur_9'];
$sp_agg4 = $_POST['sp_agg4'];
$sp_agg5 = $_POST['sp_agg5'];
$sp_agg6 = $_POST['sp_agg6'];
$sp_agg7 = $_POST['sp_agg7'];
$sp_agg8 = $_POST['sp_agg8'];
$sp_agg9 = $_POST['sp_agg9'];
$sp_wat4 = $_POST['sp_wat4'];
$sp_wat5 = $_POST['sp_wat5'];
$sp_wat6 = $_POST['sp_wat6'];
$sp_wat7 = $_POST['sp_wat7'];
$sp_wat8 = $_POST['sp_wat8'];
$sp_wat9 = $_POST['sp_wat9'];
$sp_specific_gravity_4 = $_POST['sp_specific_gravity_4'];
$sp_specific_gravity_5 = $_POST['sp_specific_gravity_5'];
$sp_specific_gravity_6 = $_POST['sp_specific_gravity_6'];
$sp_specific_gravity_7 = $_POST['sp_specific_gravity_7'];
$sp_specific_gravity_8 = $_POST['sp_specific_gravity_8'];
$sp_specific_gravity_9 = $_POST['sp_specific_gravity_9'];
$sp_water_abr_4 = $_POST['sp_water_abr_4'];
$sp_water_abr_5 = $_POST['sp_water_abr_5'];
$sp_water_abr_6 = $_POST['sp_water_abr_6'];
$sp_water_abr_7 = $_POST['sp_water_abr_7'];
$sp_water_abr_8 = $_POST['sp_water_abr_8'];
$sp_water_abr_9 = $_POST['sp_water_abr_9'];
$sp_sg_avg_2 = $_POST['sp_sg_avg_2'];
$sp_sg_avg_3 = $_POST['sp_sg_avg_3'];
$sp_wa_avg_2 = $_POST['sp_wa_avg_2'];
$sp_wa_avg_3 = $_POST['sp_wa_avg_3'];
$sp_porosity_1 = $_POST['sp_porosity_1'];
$sp_porosity_2 = $_POST['sp_porosity_2'];
$sp_porosity_3 = $_POST['sp_porosity_3'];
$sp_temp = $_POST['sp_temp'];
$remark = $_POST['remark'];
$Sheet_no = $_POST['Sheet_no'];
$wt_m = $_POST['wt_m'];

$wtr_temp_1 = $_POST['wtr_temp_1'];
$wtr_temp_2 = $_POST['wtr_temp_2'];
$wtr_temp_3 = $_POST['wtr_temp_3'];
$rt_m_1 = $_POST['rt_m_1'];
$rt_m_2 = $_POST['rt_m_2'];
$rt_m_3 = $_POST['rt_m_3'];
$ss_m1_1 = $_POST['ss_m1_1'];
$ss_m1_2 = $_POST['ss_m1_2'];
$ss_m1_3 = $_POST['ss_m1_3'];
$ss_m2_1 = $_POST['ss_m2_1'];
$ss_m2_2 = $_POST['ss_m2_2'];
$ss_m2_3 = $_POST['ss_m2_3'];
$ss_m3_1 = $_POST['ss_m3_1'];
$ss_m3_2 = $_POST['ss_m3_2'];
$ss_m3_3 = $_POST['ss_m3_3'];
$ss_m4_1 = $_POST['ss_m4_1'];
$ss_m4_2 = $_POST['ss_m4_2'];
$ss_m4_3 = $_POST['ss_m4_3'];
$ss_m5_1 = $_POST['ss_m5_1'];
$ss_m5_2 = $_POST['ss_m5_2'];
$ss_m5_3 = $_POST['ss_m5_3'];
$ssm_sub_1 = $_POST['ssm_sub_1'];
$ssm_sub_2 = $_POST['ssm_sub_2'];
$ssm_sub_3 = $_POST['ssm_sub_3'];
$ssm_sat_1 = $_POST['ssm_sat_1'];
$ssm_sat_2 = $_POST['ssm_sat_2'];
$ssm_sat_3 = $_POST['ssm_sat_3'];
$dm_ms_1 = $_POST['dm_ms_1'];
$dm_ms_2 = $_POST['dm_ms_2'];
$dm_ms_3 = $_POST['dm_ms_3'];
$bvol_1 = $_POST['bvol_1'];
$bvol_2 = $_POST['bvol_2'];
$bvol_3 = $_POST['bvol_3'];
$pv_1 = $_POST['pv_1'];
$pv_2 = $_POST['pv_2'];
$pv_3 = $_POST['pv_3'];
$por_1 = $_POST['por_1'];
$por_2 = $_POST['por_2'];
$por_3 = $_POST['por_3'];
$pd_1 = $_POST['pd_1'];
$pd_2 = $_POST['pd_2'];
$pd_3 = $_POST['pd_3'];
$wc_1 = $_POST['wc_1'];
$wc_2 = $_POST['wc_2'];
$wc_3 = $_POST['wc_3'];

		$curr_date = date("Y-m-d");



		$insert = "insert into rock (`report_no`, `ulr`, `job_no`, `lab_no`, `status`, `created_by`, `created_date`, `modified_by`, `modified_date`, `is_deleted`, `deleted_by`, `checked_by`, `bh_no`, `rock_depth`, `chk_por`,`wtr_temp_1`,`wtr_temp_2`,`wtr_temp_3`,`rt_m_1`,`rt_m_2`,`rt_m_3`,`ss_m1_1`,`ss_m1_2`,`ss_m1_3`,`ss_m2_1`,`ss_m2_2`,`ss_m2_3`,`ss_m3_1`,`ss_m3_2`,`ss_m3_3`,`ss_m4_1`,`ss_m4_2`,`ss_m4_3`,`ss_m5_1`,`ss_m5_2`,`ss_m5_3`,`ssm_sub_1`,`ssm_sub_2`,`ssm_sub_3`,`ssm_sat_1`,`ssm_sat_2`,`ssm_sat_3`,`dm_ms_1`,`dm_ms_2`,`dm_ms_3`,`bvol_1`,`bvol_2`,`bvol_3`,`pv_1`,`pv_2`,`pv_3`,`por_1`,`por_2`,`por_3`,`pd_1`,`pd_2`,`pd_3`,`wc_1`,`wc_2`,`wc_3`, `chk_com`, `desc1`, `desc2`, `desc3`, `con1`, `con2`, `con3`, `depth1`, `depth2`, `depth3`, `length1`, `length2`, `length3`, `dia1`, `dia2`, `dia3`, `ratio1`, `ratio2`, `ratio3`, `corr1`, `corr2`, `corr3`, `area1`, `area2`, `area3`, `fla1`, `fla2`, `fla3`, `par1`, `par2`, `par3`, `ppl1`, `ppl2`, `ppl3`, `str1`, `str2`, `str3`, `rate1`, `rate2`, `rate3`, `mod1`, `mod2`, `mod3`, `load1`, `load2`, `load3`, `ucs1`, `ucs2`, `ucs3`, `cor1`, `cor2`, `cor3`, `avg_ucs`, `chk_poi`, `chk_sp`, `sp_wt_st_1`, `sp_wt_st_2`, `sp_wt_st_3`, `sp_w_sur_1`, `sp_w_sur_2`, `sp_w_sur_3`, `sp_w_s_1`, `sp_w_s_2`, `sp_w_s_3`, `sp_agg1`, `sp_agg2`, `sp_agg3`, `sp_wat1`, `sp_wat2`, `sp_wat3`, `sp_specific_gravity_1`, `sp_specific_gravity_2`, `sp_specific_gravity_3`, `sp_specific_gravity`, `sp_water_abr_1`, `sp_water_abr_2`, `sp_water_abr_3`, `sp_water_abr`,`com_1`,`com_2`,`com_3`,`com_4`,`com_5`,`com_6`,`com_7`,`com_8`,`com_9`,`com_10`,`com_11`,`com_12`,`com_13`,`com_14`,`com_15`,`com_16`,`com_17`,`com_18`,`com_19`,`com_20`,`com_21`,`com_22`,`com_23`,`com_24`,`com_25`,`com_26`,`com_27`,`com_28`,`com_29`,`com_30`,`com_31`,`com_32`,`com_33`,`com_34`,`com_35`,`com_36`,`com_37`,`com_38`,`com_39`,`com_40`,`com_41`,`com_42`,`com_43`,`com_44`,`com_45`,`com_46`,`com_47`,`com_48`,`com_49`,`com_50`,`com_51`,`com_52`,`com_53`,`com_54`,`com_55`,`com_56`,`com_57`,`com_58`,`com_59`,`com_60`,`com_61`,`com_62`,`com_63`,`com_64`,`com_65`,`com_66`,`com_67`,`com_68`,`com_69`,`com_70`,`com_71`,`com_72`,`com_73`,`com_74`,`com_75`,`com_76`,`com_77`,`com_78`,`com_79`,`com_80`,`com_81`,`com_82`,`com_83`,`com_84`,`com_85`,`com_86`,`com_87`,`com_88`,`com_89`,`com_90`,`com_91`,`com_92`,`com_93`,`com_94`,`com_95`,`com_96`,`com_97`,`com_98`,`com_99`,`com_100`,`com_101`,`com_102`,`com_103`,`com_104`,`com_105`,`com_106`,`com_107`,`com_108`,`com_109`,`sp_wt_st_4`,`sp_wt_st_5`,`sp_wt_st_6`,`sp_wt_st_7`,`sp_wt_st_8`,`sp_wt_st_9`,`sp_w_s_4`,`sp_w_s_5`,`sp_w_s_6`,`sp_w_s_7`,`sp_w_s_8`,`sp_w_s_9`,`sp_w_sur_4`,`sp_w_sur_5`,`sp_w_sur_6`,`sp_w_sur_7`,`sp_w_sur_8`,`sp_w_sur_9`,`sp_agg4`,`sp_agg5`,`sp_agg6`,`sp_agg7`,`sp_agg8`,`sp_agg9`,`sp_wat4`,`sp_wat5`,`sp_wat6`,`sp_wat7`,`sp_wat8`,`sp_wat9`,`sp_specific_gravity_4`,`sp_specific_gravity_5`,`sp_specific_gravity_6`,`sp_specific_gravity_7`,`sp_specific_gravity_8`,`sp_specific_gravity_9`,`sp_water_abr_4`,`sp_water_abr_5`,`sp_water_abr_6`,`sp_water_abr_7`,`sp_water_abr_8`,`sp_water_abr_9`,`sp_sg_avg_2`,`sp_sg_avg_3`,`sp_wa_avg_2`,`sp_wa_avg_3`,`sp_porosity_1`,`sp_porosity_2`,`sp_porosity_3`,`sp_temp`,`remark`,`Sheet_no`,`wt_m`,`amend_date`) values('$report_no','$ulr','$job_no','$lab_no','0','$_SESSION[name]','$curr_date','','0000-00-00','0','','','$bh_no', '$rock_depth', '$chk_por', '$wtr_temp_1', '$wtr_temp_2', '$wtr_temp_3', '$rt_m_1', '$rt_m_2', '$rt_m_3', '$ss_m1_1', '$ss_m1_2', '$ss_m1_3', '$ss_m2_1', '$ss_m2_2', '$ss_m2_3', '$ss_m3_1', '$ss_m3_2', '$ss_m3_3', '$ss_m4_1', '$ss_m4_2', '$ss_m4_3', '$ss_m5_1', '$ss_m5_2', '$ss_m5_3', '$ssm_sub_1', '$ssm_sub_2', '$ssm_sub_3', '$ssm_sat_1', '$ssm_sat_2','$ssm_sat_3', '$dm_ms_1', '$dm_ms_2', '$dm_ms_3', '$bvol_1', '$bvol_2', '$bvol_3', '$pv_1', '$pv_2', '$pv_3', '$por_1', '$por_2', '$por_3', '$pd_1', '$pd_2', '$pd_3', '$wc_1', '$wc_2', '$wc_3','$chk_com', '$desc1', '$desc2', '$desc3', '$con1', '$con2', '$con3', '$depth1', '$depth2', '$depth3', '$length1', '$length2', '$length3', '$dia1', '$dia2', '$dia3', '$ratio1', '$ratio2', '$ratio3', '$corr1', '$corr2', '$corr3', '$area1', '$area2', '$area3', '$fla1', '$fla2', '$fla3', '$par1', '$par2', '$par3', '$ppl1', '$ppl2', '$ppl3', '$str1', '$str2', '$str3', '$rate1', '$rate2', '$rate3', '$mod1', '$mod2', '$mod3', '$load1', '$load2', '$load3', '$ucs1', '$ucs2', '$ucs3', '$cor1', '$cor2', '$cor3', '$avg_ucs', '$chk_poi', '$chk_sp', '$sp_wt_st_1', '$sp_wt_st_2', '$sp_wt_st_3', '$sp_w_sur_1', '$sp_w_sur_2', '$sp_w_sur_3', '$sp_w_s_1', '$sp_w_s_2', '$sp_w_s_3', '$sp_agg1', '$sp_agg2', '$sp_agg3', '$sp_wat1', '$sp_wat2', '$sp_wat3', '$sp_specific_gravity_1', '$sp_specific_gravity_2', '$sp_specific_gravity_3', '$sp_specific_gravity', '$sp_water_abr_1', '$sp_water_abr_2', '$sp_water_abr_3', '$sp_water_abr','$com_1','$com_2','$com_3','$com_4','$com_5','$com_6','$com_7','$com_8','$com_9','$com_10','$com_11','$com_12','$com_13','$com_14','$com_15','$com_16','$com_17','$com_18','$com_19','$com_20','$com_21','$com_22','$com_23','$com_24','$com_25','$com_26','$com_27','$com_28','$com_29','$com_30','$com_31','$com_32','$com_33','$com_34','$com_35','$com_36','$com_37','$com_38','$com_39','$com_40','$com_41','$com_42','$com_43','$com_44','$com_45','$com_46','$com_47','$com_48','$com_49','$com_50','$com_51','$com_52','$com_53','$com_54','$com_55','$com_56','$com_57','$com_58','$com_59','$com_60','$com_61','$com_62','$com_63','$com_64','$com_65','$com_66','$com_67','$com_68','$com_69','$com_70','$com_71','$com_72','$com_73','$com_74','$com_75','$com_76','$com_77','$com_78','$com_79','$com_80','$com_81','$com_82','$com_83','$com_84','$com_85','$com_86','$com_87','$com_88','$com_89','$com_90','$com_91','$com_92','$com_93','$com_94','$com_95','$com_96','$com_97','$com_98','$com_99','$com_100','$com_101','$com_102','$com_103','$com_104','$com_105','$com_106','$com_107','$com_108','$com_109','$sp_wt_st_4','$sp_wt_st_5','$sp_wt_st_6','$sp_wt_st_7','$sp_wt_st_8','$sp_wt_st_9','$sp_w_s_4','$sp_w_s_5','$sp_w_s_6','$sp_w_s_7','$sp_w_s_8','$sp_w_s_9','$sp_w_sur_4','$sp_w_sur_5','$sp_w_sur_6','$sp_w_sur_7','$sp_w_sur_8','$sp_w_sur_9','$sp_agg4','$sp_agg5','$sp_agg6','$sp_agg7','$sp_agg8','$sp_agg9','$sp_wat4','$sp_wat5','$sp_wat6','$sp_wat7','$sp_wat8','$sp_wat9','$sp_specific_gravity_4','$sp_specific_gravity_5','$sp_specific_gravity_6','$sp_specific_gravity_7','$sp_specific_gravity_8','$sp_specific_gravity_9','$sp_water_abr_4','$sp_water_abr_5','$sp_water_abr_6','$sp_water_abr_7','$sp_water_abr_8','$sp_water_abr_9','$sp_sg_avg_2','$sp_sg_avg_3','$sp_wa_avg_2','$sp_wa_avg_3','$sp_porosity_1','$sp_porosity_2','$sp_porosity_3','$sp_temp','$remark','$Sheet_no','$wt_m','$amend_date')";
		
		/* $result_of_insert = mysqli_query($conn, $insert);
		$fill = array('lab_no' => $_POST['lab_no']); */
		$result_of_insert = mysqli_query($conn, $insert);
		if($result_of_insert)
		{
			
		    $fill = array('lab_no' => $_POST['lab_no']);
			echo json_encode($fill);
		}
		else
		{
			$error = mysqli_errno($conn);
			//$result_of_insert = mysqli_query($conn, $insert);
		    $fill = array('lab_no' => $insert);
			echo json_encode($fill);
		}
		
		
		
	} else if ($_POST['action_type'] == 'view') {
		$lab_no = $_POST['lab_no'];

?>
		<div id="display_data">
			<div class="row">
				<div class="col-lg-12">
					<table border="1px solid black" align="center" width="100%" id="aaaa">
						<tr>
							<th style="text-align:center;" width="10%"><label>Actions</label></th>
							<!--<th style="text-align:center;"><label>Report No.</label></th>-->
							<th style="text-align:center;"><label>Lab No.</label></th>
							<th style="text-align:center;"><label>Job No.</label></th>



						</tr>
						<?php
						$query = "select * from rock WHERE lab_no='$lab_no' and `is_deleted`='0'";

						$result = mysqli_query($conn, $query);


						if (mysqli_num_rows($result) > 0) {
							while ($r = mysqli_fetch_array($result)) {

								if ($r['is_deleted'] == 0) {
						?>
									<tr>
										<td style="text-align:center;" width="10%">

											<a href="javascript:void(0);" class="glyphicon glyphicon-edit" onclick="editData('<?php echo $r['id']; ?>')"></a>
											<?php
											//	$val =  $_SESSION['isadmin'];
											//	if($val == 0 || $val == 5){
											?>
											<a href="javascript:void(0);" class="glyphicon glyphicon-trash" onclick="confirm('Are you sure to delete data?')?saveMetal('delete','<?php echo $r['id']; ?>'):false;"></a>
											<?php
											//	}
											?>
										</td>
										<!--<td style="text-align:center;"><?php //echo $r['report_no'];
																			?></td>-->
										<td style="text-align:center;"><?php echo $r['job_no']; ?></td>
										<td style="text-align:center;"><?php echo $r['lab_no']; ?></td>
									</tr>
						<?php
								}
							}
						}
						?>

					</table>
				</div>
			</div>

			<hr>
		</div>
		<br>
<?php

	} else if ($_POST['action_type'] == 'edit') {


		$curr_date = date("Y-m-d");

		$update = "update rock SET 
		`job_no`='$_POST[job_no]',
		`lab_no`='$_POST[lab_no]',
		`ulr`='$_POST[ulr]',
		`report_no`='$_POST[report_no]',
		`bh_no` = '$_POST[bh_no]',
		`rock_depth` = '$_POST[rock_depth]',
		`chk_por` = '$_POST[chk_por]',
		`mass_c_1` = '$_POST[mass_c_1]',
		`mass_c_2` = '$_POST[mass_c_2]',
		`mass_c_3` = '$_POST[mass_c_3]',
		`mass_d_1` = '$_POST[mass_d_1]',
		`mass_d_2` = '$_POST[mass_d_2]',
		`mass_d_3` = '$_POST[mass_d_3]',
		`sm_1` = '$_POST[sm_1]',
		`sm_2` = '$_POST[sm_2]',
		`sm_3` = '$_POST[sm_3]',
		`mass_o_1` = '$_POST[mass_o_1]',
		`mass_o_2` = '$_POST[mass_o_2]',
		`mass_o_3` = '$_POST[mass_o_3]',
		`mass_s_1` = '$_POST[mass_s_1]',
		`mass_s_2` = '$_POST[mass_s_2]',
		`mass_s_3` = '$_POST[mass_s_3]',
		`dtemp1` = '$_POST[dtemp1]',
		`dtemp2` = '$_POST[dtemp2]',
		`dtemp3` = '$_POST[dtemp3]',
		`pvol1` = '$_POST[pvol1]',
		`pvol2` = '$_POST[pvol2]',
		`pvol3` = '$_POST[pvol3]',
		`bvol1` = '$_POST[bvol1]',
		`bvol2` = '$_POST[bvol2]',
		`bvol3` = '$_POST[bvol3]',
		`den1` = '$_POST[den1]',
		`den2` = '$_POST[den2]',
		`den3` = '$_POST[den3]',
		`por1` = '$_POST[por1]',
		`por2` = '$_POST[por2]',
		`por3` = '$_POST[por3]',
		`avg_por` = '$_POST[avg_por]',
		`avg_den` = '$_POST[avg_den]',
		`chk_wtr` = '$_POST[chk_wtr]',
		`m_1_1` = '$_POST[m_1_1]',
		`m_1_2` = '$_POST[m_1_2]',
		`m_1_3` = '$_POST[m_1_3]',
		`m_2_1` = '$_POST[m_2_1]',
		`m_2_2` = '$_POST[m_2_2]',
		`m_2_3` = '$_POST[m_2_3]',
		`m_3_1` = '$_POST[m_3_1]',
		`m_3_2` = '$_POST[m_3_2]',
		`m_3_3` = '$_POST[m_3_3]',
		`wtr1` = '$_POST[wtr1]',
		`wtr2` = '$_POST[wtr2]',
		`wtr3` = '$_POST[wtr3]',
		`avg_wtr` = '$_POST[avg_wtr]',
		`chk_com` = '$_POST[chk_com]',
		`desc1` = '$_POST[desc1]',
		`desc2` = '$_POST[desc2]',
		`desc3` = '$_POST[desc3]',
		`con1` = '$_POST[con1]',
		`con2` = '$_POST[con2]',
		`con3` = '$_POST[con3]',
		`depth1` = '$_POST[depth1]',
		`depth2` = '$_POST[depth2]',
		`depth3` = '$_POST[depth3]',
		`length1` = '$_POST[length1]',
		`length2` = '$_POST[length2]',
		`length3` = '$_POST[length3]',
		`dia1` = '$_POST[dia1]',
		`dia2` = '$_POST[dia2]',
		`dia3` = '$_POST[dia3]',
		`ratio1` = '$_POST[ratio1]',
		`ratio2` = '$_POST[ratio2]',
		`ratio3` = '$_POST[ratio3]',
		`corr1` = '$_POST[corr1]',
		`corr2` = '$_POST[corr2]',
		`corr3` = '$_POST[corr3]',
		`area1` = '$_POST[area1]',
		`area2` = '$_POST[area2]',
		`area3` = '$_POST[area3]',
		`fla1` = '$_POST[fla1]',
		`fla2` = '$_POST[fla2]',
		`fla3` = '$_POST[fla3]',
		`par1` = '$_POST[par1]',
		`par2` = '$_POST[par2]',
		`par3` = '$_POST[par3]',
		`ppl1` = '$_POST[ppl1]',
		`ppl2` = '$_POST[ppl2]',
		`ppl3` = '$_POST[ppl3]',
		`str1` = '$_POST[str1]',
		`str2` = '$_POST[str2]',
		`str3` = '$_POST[str3]',
		`rate1` = '$_POST[rate1]',
		`rate2` = '$_POST[rate2]',
		`rate3` = '$_POST[rate3]',
		`mod1` = '$_POST[mod1]',
		`mod2` = '$_POST[mod2]',
		`mod3` = '$_POST[mod3]',
		`load1` = '$_POST[load1]',
		`load2` = '$_POST[load2]',
		`load3` = '$_POST[load3]',
		`ucs1` = '$_POST[ucs1]',
		`ucs2` = '$_POST[ucs2]',
		`ucs3` = '$_POST[ucs3]',
		`cor1` = '$_POST[cor1]',
		`cor2` = '$_POST[cor2]',
		`cor3` = '$_POST[cor3]',
		`avg_ucs` = '$_POST[avg_ucs]',
		`chk_poi` = '$_POST[chk_poi]',
		`gauge` = '$_POST[gauge]',
		`sam1` = '$_POST[sam1]',
		`sam2` = '$_POST[sam2]',
		`sam3` = '$_POST[sam3]',
		`sam4` = '$_POST[sam4]',
		`sam5` = '$_POST[sam5]',
		`sam6` = '$_POST[sam6]',
		`sam7` = '$_POST[sam7]',
		`sam8` = '$_POST[sam8]',
		`sam9` = '$_POST[sam9]',
		`sam10` = '$_POST[sam10]',
		`sam11` = '$_POST[sam11]',
		`d1` = '$_POST[d1]',
		`d2` = '$_POST[d2]',
		`d3` = '$_POST[d3]',
		`d4` = '$_POST[d4]',
		`d5` = '$_POST[d5]',
		`d6` = '$_POST[d6]',
		`d7` = '$_POST[d7]',
		`d8` = '$_POST[d8]',
		`d9` = '$_POST[d9]',
		`d10` = '$_POST[d10]',
		`d11` = '$_POST[d11]',
		`h1` = '$_POST[h1]',
		`h2` = '$_POST[h2]',
		`h3` = '$_POST[h3]',
		`h4` = '$_POST[h4]',
		`h5` = '$_POST[h5]',
		`h6` = '$_POST[h6]',
		`h7` = '$_POST[h7]',
		`h8` = '$_POST[h8]',
		`h9` = '$_POST[h9]',
		`h10` = '$_POST[h10]',
		`h11` = '$_POST[h11]',
		`di1` = '$_POST[di1]',
		`di2` = '$_POST[di2]',
		`di3` = '$_POST[di3]',
		`di4` = '$_POST[di4]',
		`di5` = '$_POST[di5]',
		`di6` = '$_POST[di6]',
		`di7` = '$_POST[di7]',
		`di8` = '$_POST[di8]',
		`di9` = '$_POST[di9]',
		`di10` = '$_POST[di10]',
		`di11` = '$_POST[di11]',
		`f1` = '$_POST[f1]',
		`f2` = '$_POST[f2]',
		`f3` = '$_POST[f3]',
		`f4` = '$_POST[f4]',
		`f5` = '$_POST[f5]',
		`f6` = '$_POST[f6]',
		`f7` = '$_POST[f7]',
		`f8` = '$_POST[f8]',
		`f9` = '$_POST[f9]',
		`f10` = '$_POST[f10]',
		`f11` = '$_POST[f11]',
		`pload1` = '$_POST[pload1]',
		`pload2` = '$_POST[pload2]',
		`pload3` = '$_POST[pload3]',
		`pload4` = '$_POST[pload4]',
		`pload5` = '$_POST[pload5]',
		`pload6` = '$_POST[pload6]',
		`pload7` = '$_POST[pload7]',
		`pload8` = '$_POST[pload8]',
		`pload9` = '$_POST[pload9]',
		`pload10` = '$_POST[pload10]',
		`pload11` = '$_POST[pload11]',
		`sur1` = '$_POST[sur1]',
		`sur2` = '$_POST[sur2]',
		`sur3` = '$_POST[sur3]',
		`sur4` = '$_POST[sur4]',
		`sur5` = '$_POST[sur5]',
		`sur6` = '$_POST[sur6]',
		`sur7` = '$_POST[sur7]',
		`sur8` = '$_POST[sur8]',
		`sur9` = '$_POST[sur9]',
		`sur10` = '$_POST[sur10]',
		`sur11` = '$_POST[sur11]',
		`fload1` = '$_POST[fload1]',
		`fload2` = '$_POST[fload2]',
		`fload3` = '$_POST[fload3]',
		`fload4` = '$_POST[fload4]',
		`fload5` = '$_POST[fload5]',
		`fload6` = '$_POST[fload6]',
		`fload7` = '$_POST[fload7]',
		`fload8` = '$_POST[fload8]',
		`fload9` = '$_POST[fload9]',
		`fload10` = '$_POST[fload10]',
		`fload11` = '$_POST[fload11]',
		`pstr1` = '$_POST[pstr1]',
		`pstr2` = '$_POST[pstr2]',
		`pstr3` = '$_POST[pstr3]',
		`pstr4` = '$_POST[pstr4]',
		`pstr5` = '$_POST[pstr5]',
		`pstr6` = '$_POST[pstr6]',
		`pstr7` = '$_POST[pstr7]',
		`pstr8` = '$_POST[pstr8]',
		`pstr9` = '$_POST[pstr9]',
		`pstr10` = '$_POST[pstr10]',
		`pstr11` = '$_POST[pstr11]',
		`ucom1` = '$_POST[ucom1]',
		`ucom2` = '$_POST[ucom2]',
		`ucom3` = '$_POST[ucom3]',
		`ucom4` = '$_POST[ucom4]',
		`ucom5` = '$_POST[ucom5]',
		`ucom6` = '$_POST[ucom6]',
		`ucom7` = '$_POST[ucom7]',
		`ucom8` = '$_POST[ucom8]',
		`ucom9` = '$_POST[ucom9]',
		`ucom10` = '$_POST[ucom10]',
		`ucom11` = '$_POST[ucom11]',
		`chk_tes` = '$_POST[chk_tes]',
		`avg_tes` = '$_POST[avg_tes]',`chk_sp`='$_POST[chk_sp]',`sp_wt_st_1`='$_POST[sp_wt_st_1]',`sp_wt_st_2`='$_POST[sp_wt_st_2]',`sp_wt_st_3`='$_POST[sp_wt_st_3]',`sp_w_sur_1`='$_POST[sp_w_sur_1]',`sp_w_sur_2`='$_POST[sp_w_sur_2]',`sp_w_sur_3`='$_POST[sp_w_sur_3]',`sp_w_s_1`='$_POST[sp_w_s_1]',`sp_w_s_2`='$_POST[sp_w_s_2]',`sp_w_s_3`='$_POST[sp_w_s_3]',`sp_agg1`='$_POST[sp_agg1]',`sp_agg2`='$_POST[sp_agg2]',`sp_agg3`='$_POST[sp_agg3]',`sp_wat1`='$_POST[sp_wat1]',`sp_wat2`='$_POST[sp_wat2]',`sp_wat3`='$_POST[sp_wat3]',`sp_specific_gravity_1`='$_POST[sp_specific_gravity_1]',`sp_specific_gravity_2`='$_POST[sp_specific_gravity_2]',`sp_specific_gravity_3`='$_POST[sp_specific_gravity_3]',`sp_specific_gravity`='$_POST[sp_specific_gravity]',`sp_water_abr_1`='$_POST[sp_water_abr_1]',`sp_water_abr_2`='$_POST[sp_water_abr_2]',`sp_water_abr_3`='$_POST[sp_water_abr_3]',`sp_water_abr`='$_POST[sp_water_abr]',
		`com_1`='$_POST[com_1]',
`com_2`='$_POST[com_2]',
`com_3`='$_POST[com_3]',
`com_4`='$_POST[com_4]',
`com_5`='$_POST[com_5]',
`com_6`='$_POST[com_6]',
`com_7`='$_POST[com_7]',
`com_8`='$_POST[com_8]',
`com_9`='$_POST[com_9]',
`com_10`='$_POST[com_10]',
`com_11`='$_POST[com_11]',
`com_12`='$_POST[com_12]',
`com_13`='$_POST[com_13]',
`com_14`='$_POST[com_14]',
`com_15`='$_POST[com_15]',
`com_16`='$_POST[com_16]',
`com_17`='$_POST[com_17]',
`com_18`='$_POST[com_18]',
`com_19`='$_POST[com_19]',
`com_20`='$_POST[com_20]',
`com_21`='$_POST[com_21]',
`com_22`='$_POST[com_22]',
`com_23`='$_POST[com_23]',
`com_24`='$_POST[com_24]',
`com_25`='$_POST[com_25]',
`com_26`='$_POST[com_26]',
`com_27`='$_POST[com_27]',
`com_28`='$_POST[com_28]',
`com_29`='$_POST[com_29]',
`com_30`='$_POST[com_30]',
`com_31`='$_POST[com_31]',
`com_32`='$_POST[com_32]',
`com_33`='$_POST[com_33]',
`com_34`='$_POST[com_34]',
`com_35`='$_POST[com_35]',
`com_36`='$_POST[com_36]',
`com_37`='$_POST[com_37]',
`com_38`='$_POST[com_38]',
`com_39`='$_POST[com_39]',
`com_40`='$_POST[com_40]',
`com_41`='$_POST[com_41]',
`com_42`='$_POST[com_42]',
`com_43`='$_POST[com_43]',
`com_44`='$_POST[com_44]',
`com_45`='$_POST[com_45]',
`com_46`='$_POST[com_46]',
`com_47`='$_POST[com_47]',
`com_48`='$_POST[com_48]',
`com_49`='$_POST[com_49]',
`com_50`='$_POST[com_50]',
`com_51`='$_POST[com_51]',
`com_52`='$_POST[com_52]',
`com_53`='$_POST[com_53]',
`com_54`='$_POST[com_54]',
`com_55`='$_POST[com_55]',
`com_56`='$_POST[com_56]',
`com_57`='$_POST[com_57]',
`com_58`='$_POST[com_58]',
`com_59`='$_POST[com_59]',
`com_60`='$_POST[com_60]',
`com_61`='$_POST[com_61]',
`com_62`='$_POST[com_62]',
`com_63`='$_POST[com_63]',
`com_64`='$_POST[com_64]',
`com_65`='$_POST[com_65]',
`com_66`='$_POST[com_66]',
`com_67`='$_POST[com_67]',
`com_68`='$_POST[com_68]',
`com_69`='$_POST[com_69]',
`com_70`='$_POST[com_70]',
`com_71`='$_POST[com_71]',
`com_72`='$_POST[com_72]',
`com_73`='$_POST[com_73]',
`com_74`='$_POST[com_74]',
`com_75`='$_POST[com_75]',
`com_76`='$_POST[com_76]',
`com_77`='$_POST[com_77]',
`com_78`='$_POST[com_78]',
`com_79`='$_POST[com_79]',
`com_80`='$_POST[com_80]',
`com_81`='$_POST[com_81]',
`com_82`='$_POST[com_82]',
`com_83`='$_POST[com_83]',
`com_84`='$_POST[com_84]',
`com_85`='$_POST[com_85]',
`com_86`='$_POST[com_86]',
`com_87`='$_POST[com_87]',
`com_88`='$_POST[com_88]',
`com_89`='$_POST[com_89]',
`com_90`='$_POST[com_90]',
`com_91`='$_POST[com_91]',
`com_92`='$_POST[com_92]',
`com_93`='$_POST[com_93]',
`com_94`='$_POST[com_94]',
`com_95`='$_POST[com_95]',
`com_96`='$_POST[com_96]',
`com_97`='$_POST[com_97]',
`com_98`='$_POST[com_98]',
`com_99`='$_POST[com_99]',
`com_100`='$_POST[com_100]',
`com_101`='$_POST[com_101]',
`com_102`='$_POST[com_102]',
`com_103`='$_POST[com_103]',
`com_104`='$_POST[com_104]',
`com_105`='$_POST[com_105]',
`com_106`='$_POST[com_106]',
`com_107`='$_POST[com_107]',
`com_108`='$_POST[com_108]',
`com_109`='$_POST[com_109]',
`sp_wt_st_4`='$_POST[sp_wt_st_4]',
`sp_wt_st_5`='$_POST[sp_wt_st_5]',
`sp_wt_st_6`='$_POST[sp_wt_st_6]',
`sp_wt_st_7`='$_POST[sp_wt_st_7]',
`sp_wt_st_8`='$_POST[sp_wt_st_8]',
`sp_wt_st_9`='$_POST[sp_wt_st_9]',
`sp_w_s_4`='$_POST[sp_w_s_4]',
`sp_w_s_5`='$_POST[sp_w_s_5]',
`sp_w_s_6`='$_POST[sp_w_s_6]',
`sp_w_s_7`='$_POST[sp_w_s_7]',
`sp_w_s_8`='$_POST[sp_w_s_8]',
`sp_w_s_9`='$_POST[sp_w_s_9]',
`sp_w_sur_4`='$_POST[sp_w_sur_4]',
`sp_w_sur_5`='$_POST[sp_w_sur_5]',
`sp_w_sur_6`='$_POST[sp_w_sur_6]',
`sp_w_sur_7`='$_POST[sp_w_sur_7]',
`sp_w_sur_8`='$_POST[sp_w_sur_8]',
`sp_w_sur_9`='$_POST[sp_w_sur_9]',
`sp_agg4`='$_POST[sp_agg4]',
`sp_agg5`='$_POST[sp_agg5]',
`sp_agg6`='$_POST[sp_agg6]',
`sp_agg7`='$_POST[sp_agg7]',
`sp_agg8`='$_POST[sp_agg8]',
`sp_agg9`='$_POST[sp_agg9]',
`sp_wat4`='$_POST[sp_wat4]',
`sp_wat5`='$_POST[sp_wat5]',
`sp_wat6`='$_POST[sp_wat6]',
`sp_wat7`='$_POST[sp_wat7]',
`sp_wat8`='$_POST[sp_wat8]',
`sp_wat9`='$_POST[sp_wat9]',
`sp_specific_gravity_4`='$_POST[sp_specific_gravity_4]',
`sp_specific_gravity_5`='$_POST[sp_specific_gravity_5]',
`sp_specific_gravity_6`='$_POST[sp_specific_gravity_6]',
`sp_specific_gravity_7`='$_POST[sp_specific_gravity_7]',
`sp_specific_gravity_8`='$_POST[sp_specific_gravity_8]',
`sp_specific_gravity_9`='$_POST[sp_specific_gravity_9]',
`sp_water_abr_4`='$_POST[sp_water_abr_4]',
`sp_water_abr_5`='$_POST[sp_water_abr_5]',
`sp_water_abr_6`='$_POST[sp_water_abr_6]',
`sp_water_abr_7`='$_POST[sp_water_abr_7]',
`sp_water_abr_8`='$_POST[sp_water_abr_8]',
`sp_water_abr_9`='$_POST[sp_water_abr_9]',
`sp_sg_avg_2`='$_POST[sp_sg_avg_2]',
`sp_sg_avg_3`='$_POST[sp_sg_avg_3]',
`sp_wa_avg_2`='$_POST[sp_wa_avg_2]',
`sp_wa_avg_3`='$_POST[sp_wa_avg_3]',
`sp_porosity_1`='$_POST[sp_porosity_1]',
`sp_porosity_2`='$_POST[sp_porosity_2]',
`sp_porosity_3`='$_POST[sp_porosity_3]',
`sp_temp`='$_POST[sp_temp]',
`remark`='$_POST[remark]',
`Sheet_no`='$_POST[Sheet_no]',
`wt_m`='$_POST[wt_m]',
`wtr_temp_1`='$_POST[wtr_temp_1]',
`wtr_temp_2`='$_POST[wtr_temp_2]',
`wtr_temp_3`='$_POST[wtr_temp_3]',
`rt_m_1`='$_POST[rt_m_1]',
`rt_m_2`='$_POST[rt_m_2]',
`rt_m_3`='$_POST[rt_m_3]',
`ss_m1_1`='$_POST[ss_m1_1]',
`ss_m1_2`='$_POST[ss_m1_2]',
`ss_m1_3`='$_POST[ss_m1_3]',
`ss_m2_1`='$_POST[ss_m2_1]',
`ss_m2_2`='$_POST[ss_m2_2]',
`ss_m2_3`='$_POST[ss_m2_3]',
`ss_m3_1`='$_POST[ss_m3_1]',
`ss_m3_2`='$_POST[ss_m3_2]',
`ss_m3_3`='$_POST[ss_m3_3]',
`ss_m4_1`='$_POST[ss_m4_1]',
`ss_m4_2`='$_POST[ss_m4_2]',
`ss_m4_3`='$_POST[ss_m4_3]',
`ss_m5_1`='$_POST[ss_m5_1]',
`ss_m5_2`='$_POST[ss_m5_2]',
`ss_m5_3`='$_POST[ss_m5_3]',
`ssm_sub_1`='$_POST[ssm_sub_1]',
`ssm_sub_2`='$_POST[ssm_sub_2]',
`ssm_sub_3`='$_POST[ssm_sub_3]',
`ssm_sat_1`='$_POST[ssm_sat_1]',
`ssm_sat_2`='$_POST[ssm_sat_2]',
`ssm_sat_3`='$_POST[ssm_sat_3]',
`dm_ms_1`='$_POST[dm_ms_1]',
`dm_ms_2`='$_POST[dm_ms_2]',
`dm_ms_3`='$_POST[dm_ms_3]',
`bvol_1`='$_POST[bvol_1]',
`bvol_2`='$_POST[bvol_2]',
`bvol_3`='$_POST[bvol_3]',
`pv_1`='$_POST[pv_1]',
`pv_2`='$_POST[pv_2]',
`pv_3`='$_POST[pv_3]',
`por_1`='$_POST[por_1]',
`por_2`='$_POST[por_2]',
`por_3`='$_POST[por_3]',
`pd_1`='$_POST[pd_1]',
`pd_2`='$_POST[pd_2]',
`pd_3`='$_POST[pd_3]',
`wc_1`='$_POST[wc_1]',
`wc_2`='$_POST[wc_2]',
`wc_3`='$_POST[wc_3]',
`amend_date`='$_POST[amend_date]',

		 `checked_by`=NULL WHERE `id`='$_POST[idEdit]'";

		$result_of_update = mysqli_query($conn, $update);

		$fill = array('lab_no' => $_POST['lab_no']);
		echo json_encode($fill);
	} elseif ($_POST['action_type'] == 'delete') {

		$delete = "update rock SET `is_deleted`='1',`deleted_by`='$_SESSION[name]' WHERE `report_no`='$_POST[report_no]' and `lab_no`='$_POST[lab_no]' and `job_no`='$_POST[job_no]'";

		$result_of_delete = mysqli_query($conn, $delete);

		$fill = array('lab_no' => $_POST['lab_no']);
		echo json_encode($fill);
	} elseif ($_POST['action_type'] == 'chk') {

		$qry = "SELECT * FROM rock WHERE `id`='$_POST[id]'";
		$arr = mysqli_query($conn, $qry);
		$rows1 = mysqli_num_rows($arr);
		while ($r2 = mysqli_fetch_array($arr)) {
			if ($r2['checked_by'] != "") {
				$c1c = "update rock SET `checked_by`='' WHERE `id`='$_POST[id]'";
				$result_of_delete1 = mysqli_query($conn, $c1c);
			} else {
				$cc = "update rock SET `checked_by`='$_SESSION[name]' WHERE `id`='$_POST[id]'";
				$result_of_delete2 = mysqli_query($conn, $cc);
			}
		}


		$fill = array('lab_no' => $_POST['lab_no']);
		echo json_encode($fill);
	}
	exit;
}
?>